#!/bin/zsh

cd `dirname $0`

export defm=-Dcustom_main=nanojs_main

export srcd="           \
    ../../cvm/nanojs    \
    ../../cvm/nanolib   \
    ../../capi/dash     \
    ../../host/unix     \
"

sh ../../mkwrapper
