#!/bin/zsh

cd `dirname $0`

export defm=-Dcustom_main=nanojs_main

export srcd="           \
    ../../vm/nanojs     \
    ../../api/dash      \
    ../../vm/nanojslib  \
    ../../host/unix     \
"

sh ../../mkwrapper
