#!/bin/zsh

cd `dirname $0`

export defm=-Dcustom_main=UMain

export srcd="           \
    ../../api/ui        \
    ../../api/dash      \
    ../../api/low       \
    ../../api/reflect   \
"

sh ../../mkwrapper
