#!/bin/zsh

cd `dirname $0`

export defm=-Dui_main=main

export srcd="           \
    ../../api/ui        \
    ../../api/dash      \
    ../../api/low       \
    ../../api/reflect   \
"

sh ../../mkwrapper
