#!/bin/zsh

cd `dirname $0`

export defm=-Dcustom_main=MMain

export srcd="               \
    ../../cppapi/master     \
    ../../cppapi/dash       \
    ../../cpppapi/low       \
    ../../cppapi/reflect    \
    ../../host/console      \
"

sh ../../mkgen
