#!/bin/zsh

cd `dirname $0`

export defm=-Dcustom_main=MMain

export srcd="           \
    ../../capi/master   \
    ../../capi/dash     \
    ../../capi/low      \
    ../../capi/reflect  \
    ../../host/console  \
"

sh ../../mkwrapper
