#!/bin/zsh

# these parameters need to be provided externally:
#   srcd: header and source directories;
#   defm: defined macros.

# build mkmk tool.
mkmk=`dirname $0`/mkmk
if [ ! -f $mkmk.exe ]; then
    c++ --std=c++20 -O3 -o $mkmk.exe $mkmk.cpp
fi

# generate makefile.
incd=
for item in $srcd; do
    incd="$incd -I$item"
done

mkdir -p obj

$mkmk.exe                                               \
    --compile-cmd "c++ $defm $incd --std=c++20 -c -o "  \
    --link-cmd    "c++ -o "                             \
    --header-dirs $srcd                                 \
    --source-dirs $srcd                                 \
    --output-file out.exe                               \
    --object-dir  obj                                   \
    > makefile
