#!/bin/zsh

cd `dirname $0`

export defm=-Dcustom_main=MMain

export srcd="           \
    ../../api/master    \
    ../../api/dash      \
    ../../api/low       \
    ../../api/reflect   \
"

sh ../../mkwrapper
