#!/bin/zsh

cd `dirname $0`

export defm=-Dcustom_main=SMain

export srcd="               \
    ../../cppapi/system     \
    ../../cppapi/dash       \
    ../../cppapi/low        \
    ../../cppapi/reflect    \
    ../../host/console      \
"

sh ../../mkgen
