#!/bin/zsh

cd `dirname $0`

export defm=

export srcd="               \
    ../../host/console      \
    ../../cppapi/cson       \
    ../../cppapi/dash       \
    ../../cppapi/low        \
    ../../cppapi/master     \
    ../../cppapi/net        \
    ../../cppapi/reflect    \
    ../../cppapi/system     \
    ../../cppapi/ui         \
    ../../cppvm/nanojs      \
    ../../cppvm/nanolib     \
"

sh ../../mkgen
