#!/bin/zsh

cd `dirname $0`

export defm=-Dcustom_main=UMain

export srcd="           \
    ../../capi/ui       \
    ../../capi/dash     \
    ../../capi/low      \
    ../../capi/reflect  \
    ../../host/unix     \
"

sh ../../mkwrapper
