#!/bin/zsh

cd `dirname $0`

export defm=-Dcustom_main=reflect_main

export srcd="               \
    ../../cppapi/reflect    \
    ../../cppapi/dash       \
    ../../host/console      \
"

sh ../../mkgen
