#!/bin/zsh

cd `dirname $0`

export defm=-Dcustom_main=SMain

export srcd="           \
    ../../api/system    \
    ../../api/dash      \
    ../../api/low       \
    ../../api/reflect   \
"

sh ../../mkwrapper
