#!/bin/zsh

cd `dirname $0`

export _exec=app.exe
export _objd=obj
export _mkmk=../../mkmk

export _dirs="        \
    ../../cpp/ui      \
    ../../cpp/dash    \
    ../../cpp/reflect \
"

sh ../../mkbuild
