#!/bin/zsh

cd `dirname $0`

export defm=-Dmaster_main=main

export srcd="           \
    ../../cpp/master    \
    ../../cpp/dash      \
    ../../cpp/low       \
    ../../cpp/reflect   \
"

sh ../../mkbuild
