#!/bin/zsh

cd `dirname $0`

export _exec=app.exe
export _objd=obj
export _mkmk=../../mkmk

export _dirs="        \
    ../../cpp/master  \
    ../../cpp/dash    \
    ../../cpp/nanojs  \
    ../../cpp/reflect \
    ../../cpp/sjson   \
"

sh ../../mkbuild
