#!/bin/zsh

cd `dirname $0`

export defm=-Dcustom_main=nanojs_main

export srcd="           \
    ../../cppvm/nanojs  \
    ../../cppvm/nanolib \
    ../../cppapi/dash   \
    ../../host/console  \
"

sh ../../mkgen
