#!/bin/zsh

cd `dirname $0`

export defm=

export srcd="           \
    ../../host/unix     \
    ../../api/cson      \
    ../../api/dash      \
    ../../api/low       \
    ../../api/master    \
    ../../api/net       \
    ../../api/reflect   \
    ../../api/system    \
    ../../api/ui        \
    ../../vm/nanojs     \
    ../../vm/nanojslib  \
"

sh ../../mkwrapper
