#!/bin/zsh

cd `dirname $0`

export defm=

export srcd="           \
    ../../host/unix     \
    ../../capi/cson     \
    ../../capi/dash     \
    ../../capi/low      \
    ../../capi/master   \
    ../../capi/net      \
    ../../capi/reflect  \
    ../../capi/system   \
    ../../capi/ui       \
    ../../cvm/nanojs    \
    ../../cvm/nanolib   \
"

sh ../../mkwrapper
